blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='blog',),
    path('<int:blog_id>/', views.detail, name='detail',),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateField(auto_now=False, auto_now_add=False,)

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(r):
    blogs = Blog.objects.order_by('-date')
    return render(r, 'blog/all_blogs.html', {'blogs':blogs})

def detail(r, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(r, 'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(r):
    projects = Project.objects.all()
    return render(r, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}
Артём написал {{ blogs.count }} пост{{ blogs.count | pluralize }}

{% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id  %}"><h1>{{blog.title}}</h1></a>
    <h5>{{blog.date}}</h5>
    <h2>{{blog.discription}}</h2>
 
 
{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}


{% block content %}
<a>
<h5>{{ blog.title }}</h5>
<br>
{{ blog.text }}
</p>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>


<style>
  .bg-color {
    background-color: rgba(63, 176, 233, 0.099);
}


</style>


<html lang="en">
  <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>oneoopss's Site()</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
      <link rel="shortcut icon" href="/media/logo.png">
  </head>
  <body class="body">

    <nav class="navbar navbar-expand-lg bg-color">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Домой</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://vk.com/oneoopss" target="_blank">Вконтакте</a>
              </li>
              </li>
              <li class="nav-item">
              </li>
            </ul>
            <form class="d-flex" role="search">
                <img src="/media/logo.png" width="60" height="60">
            </form>
          </div>
        </div>
      </nav>
    

      {% block content %}
      {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<style>

.item {
  display: inline-block;
  padding: 10px 20px;
  border: none;
}

.center {
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
}
.no-link {
  text-decoration: none;
  color: inherit;
}
</style>
<h1 class="center display-5">сайт oneoopss</h1>


<button type="button" class="btn btn-info"><a href="{% url 'blog:blog' %}"class="no-link">Все блоги</a></button>
<button type="button" class="btn btn-info"><a href="{% static 'portfolio/resume.pdf' %}"class="no-link"target="_blank">Резюме</a></button>

<div class="center"><img src="{% static 'portfolio/my_photo.JPEG' %}", height="300", width="400", ></div>


<h1 class="display-6">Мои проекты: </h1>
<hr>


{% for  project in projects %}
<div class="item">

    <p class="display-6">{{ project.title }}</p>
    <p>{{ project.discription }}</p>



    {% if project.url %}
        <a href="{{ project.url }}">
            <img src="{{ project.image.url }}", height="100", width="100">
        </a>

    <!-- <a href="{{ project.url }}">Link</a> -->
    {% else %}
    <img src="{{ project.image.url }}", height="100", width="100">
    {% endif %}
</div>
{% endfor %}

{% endblock %}